package forme;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class PocetnaForma extends javax.swing.JFrame {

    private JButton jButtonIzmeniRezervaciju;
    private JButton jButtonDodajRezervaciju;
    private Image pozadinaSlika;
    private JLabel JLabelUlogovani;

    /**
     * Creates new form PocetnaForma
     */
    public PocetnaForma() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setResizable(false);
        dodajSadrzaj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void dodajSadrzaj() {
        URL url = getClass().getResource("/resources/BedHead.png");
        pozadinaSlika = (url != null) ? new ImageIcon(url).getImage() : null;

        JPanel pozadinaPanel = new JPanel(new GridBagLayout()) {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (pozadinaSlika != null) {
                    g.drawImage(pozadinaSlika, 0, 0, getWidth(), getHeight(), this);
                } else {
                    g.setColor(Color.DARK_GRAY);
                    g.fillRect(0, 0, getWidth(), getHeight());
                }
            }
        };
        setContentPane(pozadinaPanel);

        JLabelUlogovani = new JLabel();
        JLabelUlogovani.setForeground(Color.BLACK);
        JLabelUlogovani.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));

        jButtonIzmeniRezervaciju = new JButton("Izmeni rezervaciju");
        jButtonDodajRezervaciju = new JButton("Dodaj rezervaciju");

        ImageIcon icon1 = new ImageIcon(getClass().getResource("/resources/edit.png"));
        Image img1 = icon1.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        jButtonIzmeniRezervaciju.setIcon(new ImageIcon(img1));
        
        ImageIcon icon2 = new ImageIcon(getClass().getResource("/resources/doc.png"));
        Image img2 = icon2.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        jButtonDodajRezervaciju.setIcon(new ImageIcon(img2));

        jButtonIzmeniRezervaciju.setPreferredSize(new Dimension(220, 45));
        jButtonDodajRezervaciju.setPreferredSize(new Dimension(220, 45));

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.gridx = 0;

        gbc.gridy = 0;
        pozadinaPanel.add(JLabelUlogovani, gbc);

        gbc.gridy = 1;
        pozadinaPanel.add(jButtonIzmeniRezervaciju, gbc);

        gbc.gridy = 2;
        pozadinaPanel.add(jButtonDodajRezervaciju, gbc);

        setLocationRelativeTo(null);
        revalidate();
        repaint();
    }

    public JButton getjButtonIzmeniRezervaciju() {
        return jButtonIzmeniRezervaciju;
    }

    public JButton getjButtonDodajRezervaciju() {
        return jButtonDodajRezervaciju;
    }

    public void addIzmeniRezervacijuActionListener(ActionListener actionListener) {
        jButtonIzmeniRezervaciju.addActionListener(actionListener);
    }

    public void addDodajRezervacijuActionListener(ActionListener actionListener) {
        jButtonDodajRezervaciju.addActionListener(actionListener);
    }

    public JLabel getjLabelUlogovani() {
        return JLabelUlogovani;
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
