package forme;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

public class PocetnaForma extends javax.swing.JFrame {

    private JButton jButtonIzmeniRezervaciju;
    private JButton jButtonDodajRezervaciju;
    private Image pozadinaSlika;

    /**
     * Creates new form PocetnaForma
     */
    public PocetnaForma() {
        initComponents();
        dodajSadrzaj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PocetnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PocetnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PocetnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PocetnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PocetnaForma().setVisible(true);
            }
        });
    }

    private void dodajSadrzaj() {
        URL url = getClass().getResource("/resources/BedHead.png");
        pozadinaSlika = (url != null) ? new ImageIcon(url).getImage() : null;

        JPanel pozadinaPanel = new JPanel(new GridBagLayout()) {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (pozadinaSlika != null) {
                    g.drawImage(pozadinaSlika, 0, 0, getWidth(), getHeight(), this);
                } else {
                    g.setColor(Color.DARK_GRAY);
                    g.fillRect(0, 0, getWidth(), getHeight());
                }
            }
        };
        setContentPane(pozadinaPanel);

        jButtonIzmeniRezervaciju = new JButton("Izmeni rezervaciju");
        jButtonDodajRezervaciju = new JButton("Dodaj rezervaciju");

        jButtonIzmeniRezervaciju.setPreferredSize(new Dimension(220, 45));
        jButtonDodajRezervaciju.setPreferredSize(new Dimension(220, 45));

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.gridx = 0;

        gbc.gridy = 0;
        pozadinaPanel.add(jButtonIzmeniRezervaciju, gbc);

        gbc.gridy = 1;
        pozadinaPanel.add(jButtonDodajRezervaciju, gbc);

        setSize(800, 600);
        setLocationRelativeTo(null);
        revalidate();
        repaint();
    }

    public JButton getjButtonIzmeniRezervaciju() {
        return jButtonIzmeniRezervaciju;
    }

    public JButton getjButtonDodajRezervaciju() {
        return jButtonDodajRezervaciju;
    }

    public void addIzmeniRezervacijuActionListener(ActionListener actionListener) {
        jButtonIzmeniRezervaciju.addActionListener(actionListener);
    }

    public void addDodajRezervacijuActionListener(ActionListener actionListener) {
        jButtonDodajRezervaciju.addActionListener(actionListener);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
