#To change this license header, choose License Header in Project Properties.
#To change this template file, chose Tools | Templates
#and open the template in the editor.

#Database Configuration
url = jdbc:mysql://localhost:3306/frizerskiSalon
username = root
password = 